name: PaintWar
main: io.github.jfischer00.paintwarplugin.PaintWarPlugin
author: JFischer00
website: http://dev.bukkit.org/bukkit-plugins/paint-war
depend: [WorldEdit, Vault, Essentials]
version: 1.0
commands:
  pw:
    description: PaintWar base command.
    usage: /<command> [action]
    permission: paintwar.base
    permission-message: You may not use PaintWar.
permissions:
    paintwar.base:
        default: true
    paintwar.create:
        default: op
    paintwar.delete:
        default: op
    paintwar.start:
        default: op
    paintwar.stop:
        default: op
    paintwar.list:
        default: true
    paintwar.status:
        default: true
    paintwar.join:
        default: true
    paintwar.leave:
        default: true